  # gcloud container node-pools create a100-spot-pool \
  # --cluster sizhang-ray-gpu \
  # --region us-central1-a \
  # --project tpu-vm-gke-testing \
  # --machine-type a2-highgpu-2g \
  # --spot \
  # --num-nodes 3 \
  # --quiet

apiVersion: v1
kind: Pod
metadata:
  name: a100-2gpu-test
spec:
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    command: ["sh", "-c", "nvidia-smi && sleep 60"]
    resources:
      limits:
        nvidia.com/gpu: 2
      requests:
        nvidia.com/gpu: 2
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-a100
    cloud.google.com/gke-nodepool: a100-spot-pool
  # tolerations:
  # - key: "cloud.google.com/gke-spot"
  #   operator: "Equal"
  #   value: "true"
  #   effect: "NoSchedule"
  # - key: "nvidia.com/gpu"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  # restartPolicy: Never
